_model_path: models/OCR/nepali_lpr_20250729_112957
aug_blur_limit: 3
aug_rotate_limit: 7
batch_size: 8
height: 32
label_padding_token: 68
max_text_length: 18
train_epochs: 200
train_workers: 8
vocab:
- "\u0915"
- "\u0916"
- "\u0917"
- "\u091A"
- "\u091C"
- "\u091D"
- "\u0924"
- "\u0926"
- "\u0928"
- "\u092A"
- "\u092C"
- "\u092E"
- "\u092F"
- "\u0930"
- "\u0932"
- "\u0935"
- "\u0936"
- "\u0938"
- "\u0966"
- "\u0967"
- "\u0968"
- "\u0969"
- "\u096A"
- "\u096B"
- "\u096C"
- "\u096D"
- "\u096E"
- "\u096F"
width: 256
